BEGIN TRANSACTION;
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('PGH','Robertson (red), Oaks Satellite (blue), Campus Loop (green)','marker_bus.png',29.721787,-95.344055, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Garrison Stop','Robertson (red)','marker_bus.png',29.72407,-95.34788, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Robertson Lot 15D','Robertson (red)','marker_bus.png',29.724242,-95.349526, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Robertson Lot 12A','Robertson (red)','marker_bus.png',29.720893,-95.351039, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Robertson Lot 12B','Robertson (red)','marker_bus.png',29.721825,-95.351254, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Robertson Lot 12B II','Robertson (red)','marker_bus.png',29.723273,-95.350154, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Robertson Lot 11A','Robertson (red)','marker_bus.png',29.7206,-95.34875, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Stop on Cullen','Robertson (red), Oaks Satellite (blue)','marker_bus.png',29.72085,-95.34773, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Lamar Fleming','Robertson (red), Campus Loop (green), Oaks Satellite (blue)','marker_bus.png',29.72198,-95.34544, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Stop on Cullen 2','Oaks Satellite (blue)','marker_bus.png',29.72073,-95.34732, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Cambridge Oaks','Oaks Satellite (blue)','marker_bus.png',29.7173,-95.34908, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Cullen Oaks','Oaks Satellite (blue)','marker_bus.png',29.71478,-95.34919, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Economy Lot1 8A','Oaks Satellite (blue)','marker_bus.png',29.71395,-95.34826, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Economy Lot2 9C','Oaks Satellite (blue)','marker_bus.png',29.71592,-95.34758, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Economy Lot3 9B','Oaks Satellite (blue)','marker_bus.png',29.71699,-95.34863, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Welcome center','Campus Loop (green)','marker_bus.png',29.71909,-95.34004, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('University Dr','Eastwood (tan)','marker_bus.png',29.71843,-95.33697, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Behind Chinese Star','Eastwood (tan)','marker_bus.png',29.72149,-95.33674, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Near Spur','Eastwood (tan)','marker_bus.png',29.72505,-95.33772, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Eastwood TC','Eastwood (tan)','marker_bus.png',29.72822,-95.33558, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('University Center','Bayou Oaks (purple), Campus Loop (green), Eastwood (tan)','marker_bus.png',29.71985,-95.34133, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Alumni Center','Campus Loop (green)','marker_bus.png',29.72537,-95.34562, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Music School Ent 16','Campus Loop (green)','marker_bus.png',29.7255,-95.34368, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Architecture','Campus Loop (green)','marker_bus.png',29.72486,-95.34173, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Law Village','Campus Loop (green)','marker_bus.png',29.72482,-95.3393, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Law Center','Campus Loop (green)','marker_bus.png',29.7226,-95.33818, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Moody Towers','Campus Loop (green)','marker_bus.png',29.7165,-95.34195, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Near Moody Towers','Bayou Oaks (purple)','marker_bus.png',29.71793,-95.3411, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Lot 4A','Bayou Oaks (purple)','marker_bus.png',29.71541,-95.34136, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Bayou Oaks Apts','Bayou Oaks (purple)','marker_bus.png',29.71299,-95.34108, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Recreation and Wellness Center','Bayou Oaks (purple)','marker_bus.png',29.71774,-95.33946, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('ERP','Eastwood (tan)','marker_bus.png',29.719225,-95.326223, "", 4);
INSERT INTO "interests" (name, description, marker_icon, latitude, longitude, url, category_id) VALUES('Calhoun Lofts','Campus Loop (green)','marker_bus.png',29.721932,-95.33802, "", 4);
COMMIT;
